<?php
/**
 * @file
 * Modifications to the default build routine for vagrant development
 */
/**
 * Implements hook_cis_service_instance_options_alter().
 *
 * These are recommended defaults when modifying the build routine for service
 * instances created at run time. These serve as model defaults but if you
 * want to change these you can disable this module and add your own in
 * manually.
 */
function vagrant_cis_dev_cis_service_instance_options_alter(&$options, $course, $service) {
  // devel so we can debug consistently
  $options['en'][] = 'devel';
  // UI modules
  $options['en'][] = 'context_ui';
  $options['en'][] = 'field_ui';
  $options['en'][] = 'views_ui';
  // environmental indicator so we now what we are working on
  $options['en'][] = 'environment_indicator';
}

/**
 * Implements hook_cis_service_instance_job_file_alter().
 */
function vagrant_cis_dev_cis_service_instance_job_file_alter(&$content, $course, $service, $service_instance) {
  // force these to run last as they might get inserted prior to the setting
  // that enables in a typical build
  $content .= 'drush vset preprocess_css 0' . "\n";
  $content .= 'drush vset preprocess_js 0' . "\n";
  $content .= 'drush vset admin_menu_dropdown_default 0' . "\n";
}
