<?php
/**
 * @file
 * Modifications to the default build routine for vagrant development
 */
/**
 * Implements hook_cis_service_instance_options_alter().
 *
 * These are recommended defaults when modifying the build routine for service
 * instances created at run time. These serve as model defaults but if you
 * want to change these you can disable this module and add your own in
 * manually.
 */
function vagrant_cis_dev_cis_service_instance_options_alter(&$options, $course, $service) {
  // disable performance optimizations
  $options['vset'][] = 'preprocess_css 0';
  $options['vset'][] = 'preprocess_js 0';
  // devel so we can debug consistently
  $options['en'][] = 'devel';
  // UI modules
  $options['en'][] = 'context_ui';
  $options['en'][] = 'field_ui';
  $options['en'][] = 'views_ui';
  // environmental indicator so we now what we are working on
  $options['en'][] = 'environment_indicator';
}

/**
 * Implements hook_cis_service_instance_TOOL_options_alter().
 */
function vagrant_cis_dev_cis_service_instance_courses_options_alter(&$options, $course, $service) {
  // mooc should have some accessibility tests to play with OOTB
  $options['en'][] = 'textbook_wcag20aa';
}
